# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Specify the logs_bucket field to resolve the error
options:
  logging: CLOUD_LOGGING_ONLY # You can use CLOUD_LOGGING_ONLY or NONE, depending on your preference

# [START cloudbuild_basic_config]
steps:
  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/abc-jobs-402104/abc-jobs-repository/abc-jobs-frontend:latest",
        "."
      ]

  # Docker Push Offers
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/abc-jobs-402104/abc-jobs-repository/abc-jobs-frontend:latest",
      ]
  

  # Set Cluster, Region, and Zone environment variables
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container clusters get-credentials autopilot-cluster-abc-jobs \
        --region us-central1 \
        --project abc-jobs-402104

    # Deploy
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        kubectl apply -f deployment/k8s-deployment.yaml

  # Set Cluster, Region, and Zone environment variables
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        kubectl rollout restart deployment offers



  # # Entrypoint, timeout and environment variables
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'gcloud'
  #   timeout: 240s
  #   args: ['compute', 'instances',
  #          'create-with-container', 'my-vm-name',
  #          '--container-image',
  #          'us-central1-docker.pkg.dev/architecture-experiment/experiment/offers:latest']
  #   env:
  #     - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  #     - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'

# [END cloudbuild_basic_config]