export const mockData_project = [
  {
    name: 'Project 1',
    description: 'Description of Project 1',
    code: 'P001',
    profiles: ['Profile A', 'Profile B'],
  },
  {
    name: 'Project 2',
    description: 'Description of Project 2',
    code: 'P002',
    profiles: [],
  },
  {
    name: 'Project 3',
    description: 'Description of Project 3',
    code: 'P003',
    profiles: ['Profile E', 'Profile F'],
  },
  {
    name: 'Project 4',
    description: 'Description of Project 4',
    code: 'P004',
    profiles: ['Profile G', 'Profile H'],
  },
  {
    name: 'Project 5',
    description: 'Description of Project 5',
    code: 'P005',
    profiles: ['Profile I', 'Profile J'],
  },
  {
    name: 'Project 6',
    description: 'Description of Project 6',
    code: 'P006',
    profiles: ['Profile K', 'Profile L'],
  },
  {
    name: 'Project 7',
    description: 'Description of Project 7',
    code: 'P007',
    profiles: ['Profile M', 'Profile N'],
  },
  {
    name: 'Project 8',
    description: 'Description of Project 8',
    code: 'P008',
    profiles: ['Profile O', 'Profile P'],
  },
  {
    name: 'Project 9',
    description: 'Description of Project 9',
    code: 'P009',
    profiles: ['Profile Q', 'Profile R'],
  },
  {
    name: 'Project 10',
    description: 'Description of Project 10',
    code: 'P010',
    profiles: ['Profile S', 'Profile T'],
  },
  {
    name: 'Project 11',
    description: 'Description of Project 11',
    code: 'P011',
    profiles: ['Profile U', 'Profile V'],
  },
  {
    name: 'Project 12',
    description: 'Description of Project 12',
    code: 'P012',
    profiles: ['Profile W', 'Profile X'],
  },
  {
    name: 'Project 13',
    description: 'Description of Project 13',
    code: 'P013',
    profiles: ['Profile Y', 'Profile Z'],
  },
  {
    name: 'Project 14',
    description: 'Description of Project 14',
    code: 'P014',
    profiles: ['Profile AA', 'Profile BB'],
  },
  {
    name: 'Project 15',
    description: 'Description of Project 15',
    code: 'P015',
    profiles: ['Profile CC', 'Profile DD'],
  },
];
